# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Albin
tagline:          'A collection of personal things that needed linking'
description:      'A collection of personal things that needed linking.'
url:              http://albinstjerna.se
baseurl:          /

author:
  name:           'Albin Stjerna'
  url:            https://twitter.com/albinst

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/albins/albin.github.io
