# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins: [jekyll-paginate, jekyll-gist, jemoji]

# Permalinks
permalink:        pretty

# Setup
title:            Albin
tagline:          ''
description:      ''
url:              http://albinstjerna.se
baseurl:          /

author:
  name:           'Albin Stjerna'
  url:            https://twitter.com/albinst

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/albins/albin.github.io
