# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins: [jekyll-paginate, jekyll-gist, jemoji, jekyll-github-metadata]

# Permalinks
permalink:        pretty

# Setup
title:            Amanda
tagline:          ''
description:      ''
url:              https://amandastjerna.se

author:
  name:           'Amanda Stjerna'

paginate:         5

# Custom vars
version:          2.1.0
